blank_issues_enabled: true
contact_links:
  - name: test
    url: https://github.com/hiro-bin/issue_test
    about: test
  - name: test
    url: https://github.com/hiro-bin/issue_test
    about: test
